NeW DB copy service message integration
Ensembl/ensembl-prodinf-legacy-srv pull request #66
Opened 2021-02-08 07:48 UTC by marcoooo

DB APP message integration: db app display new message from job_progress from dba copy service
Bugfix : Handover catch Exception

2021-02-12 17:53 UTC, luca-drf requested changes

2021-02-12 17:53 UTC, luca-drf commented on db_app.py
> +            if last_job_progress != None:
```suggestion
            if last_job_progress is not None:
```

2021-02-12 18:33 UTC, marcoooo commented on db_app.py
> +            if last_job_progress != None:
Ohhhh shame on me!

2021-02-15 18:46 UTC, luca-drf approved these changes

2021-03-03 16:52 UTC, merged